### PR TITLE
feat: add phantom as featured

### PR DESCRIPTION
**Pull request by helciofranco**
- Closes https://github.com/FuelLabs/fuel-connectors/issues/174

---

`Phantom Wallet` is now featured in the Solana wallet connectors list. 
Previously, it required installation or accessing the “All Wallets” list to be found.

| 📷  Demo |
| --- |
| Screenshot 2024-08-07 at 12 00 59 |

### CODE REVIEW

**Review by arthurgeron — CHANGES_REQUESTED** [review]
Code looks great, but I've found two bugs:

- It duplicates the Phantom option in Solana connector when [Phantom Wallet](https://chrome.google.com/webstore/detail/bfnaelmomeimhlpmgjnjophhpkkoljpa) is installed:
CleanShot 2024-08-06 at 16 34 36

- PR Audit check is failing

**Comment by helciofranco** [comment]
Nice catch @arthurgeron I'll take a look on it

**Comment by helciofranco** [comment]
@arthurgeron done, should be all set.

Now the phantom connector will be visible only if there's no phantom in the `window`.

Regarding the `audit`, it's a known issue in our repos right now and there's no resolution yet (that package haven't published a fix).

Ready for review again.

**Review by arthurgeron — DISMISSED** [review]
LGTM

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
can the same situation mentioned by @arthurgeron happen with trust and okx wallet  as well?

**Comment by helciofranco** [comment]
@LuizAsFight great question, that issue may affect those connectors too.

we can decide between two solutions here:
1. fix for those connectors (okx and trust wallet)
2. remove them and keep only phantom as featured

which option is better?

**Comment by LuizAsFight** [comment]
@helciofranco let's keep Trust and Phantom. okx can be removed from featured

**Review by arthurgeron — APPROVED** [review]
LGTM

**Review by LuizAsFight — APPROVED** [review]

**Pull request merged**
