### PR TITLE
fix: maintain disconnected after refresh

### LINKED ISSUE #136: [WalletConnectConnector] - Maintain disconnected after refresh
If you connect to metamask wallet.. then refresh, click on disconnect... then refresh again

you will be connected again to metamask wallet.

this issue aims to:
- if the user intentionally clicked on disconnect, after refreshing he should be still disconnected
- if the user didn't click on disconnect, after refreshing he should be still connected (this is already working, just mentioned here to make sure this behavior don't get broken after fixing this issue)

### PR DESCRIPTION
**Pull request by mvares**
- Closes: #136

### CODE REVIEW

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
thanks for contributing.

this line you removed is needed to maintain user connected after refresh.

**Comment by mvares** [comment]
Hey @LuizAsFight! Would you explain it for me? I thought that goal of issue was fixed it.

**Comment by LuizAsFight** [comment]
> Hey @LuizAsFight! Would you explain it for me? I thought that goal of issue was fixed it.
> 
> PS: I already know what I did wrong

yes, the function removed is needed to restore the connection after the user refreshes the page when using walletConnectConnector, it cannot be removed.

the work on this issue is to make the disconnect for walletConnect be permanent, instead of `reconnectable` after refresh.

**Review by LuizAsFight — APPROVED** [review]
good work!

**Pull request merged**
