### PR TITLE
feat(faucet): improve faucet UX

### PR DESCRIPTION
**Pull request by LeoCourbassier**
* Improves UX by redirecting to the faucet link with `returnUrl` set

### CODE REVIEW

**Comment by LeoCourbassier** [comment]
Fixes https://github.com/FuelLabs/fuel-connectors/issues/180

**Comment by LeoCourbassier** [comment]
Desktop view: 
image

**Comment by luizstacio** [comment]
The problem with iframe is not mobile but Safari, or any other browser that not allow third party cookies. @LuizAsFight 

Let's use just one way to consolidate it. Redirect always for this application will look good, as we don't have middle states.

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
the flow is not working as expected, you need to be able to faucet and come back to same screen without needing to close any popup

**Review by LuizAsFight — APPROVED** [review]

**Pull request merged**
