### PR TITLE
feat: Persist BurnerWallet provider in localStorage

### PR DESCRIPTION
**Pull request by mvares**
- Closes: #170

### CODE REVIEW

**Comment by mvares** [comment]
Hey @LuizAsFight! Can you take a look at this?

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
@mvares it is still losing the connection after I refresh the page

how you can reproduce:
1- run a local node (you can use `pnpm node:up` in the fuels-wallet repo for instance)
2- change "examples/react-app/src/main.tsx", include provider in Burner connector:
```
            new BurnerWalletConnector({
              fuelProvider: Provider.create('http://localhost:4000/v1/graphql'),
            }),
```
3- run the examples/react-app with `pnpm dev`
4- connect to Burner Wallet, then refresh the page

you will see the connection will be lost when refreshing

**Comment by LuizAsFight** [comment]
closing it as was already fixed in https://github.com/FuelLabs/fuel-connectors/commit/e98f5623d46404dfc193e7a0c2319dba699b2cd8

**Comment by LuizAsFight** [comment]
reopening as adding to localstorage is a good feature anyway

**Review by LuizAsFight — APPROVED** [review]

**Pull request merged**
